spring:
  profiles:
    active: dev
  application:
    name: PRM

  data:
    redis:
      url: ${REDIS_URL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
#        enabled: false
        options:
          model: gemma2:2b
          temperature: 0.6
      embedding:
#        enabled: false
        options:
          model: nomic-embed-text

    vectorstore:
      pgvector:
        table-name: vector_store
        dimension: 768
        initialize-schema: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  refresh-token:
    expiration-days: ${RFT_EXPIRATION}
  mail:
    from: nguyenminhnguyen08112004@gmail.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: prm/products
outfit-service:
  base-url: http://localhost:8000   # đổi thành URL thật của Python FastAPI service khi deploy
  internal-api-key: ${OUTFIT_INTERNAL_API_KEY}